# Generated by Django 5.0.1 on 2024-01-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ITEM1', 'Tech & IT'), ('ITEM2', 'Hobbies & Fun'), ('ITEM2', 'Sports & Rec'), ('ITEM2', 'Cooking & Food'), ('ITEM2', 'Art & Culture')], default='ITEM1', max_length=50),
        ),
    ]
